### ISSUE TITLE
Tracking issue of unstable features that have to be stabilized before publishing to crates.io

### ISSUE THREAD

**Issue by Luro02** [Luro02/path-sanitizer#6]
The implementation uses a number of unstable features, which have to be stabilized, before it can be published to crates.io.

- [ ] the `Platform` trait uses generic associated lifetimes: https://github.com/rust-lang/rust/issues/44265
- [ ] `const_generics_defaults` would be nice to have, but not required
- [ ] `type_alias_impl` is not required but very useful to reduce typing: https://github.com/rust-lang/rust/issues/63063
